# Language settings
language: en_US

# Combat settings
combat:
  # Duration of combat tag in seconds
  duration: 20

  # Commands that are blocked during combat
  blocked_commands:
    - "rtp"
    - "tp"
    - "teleport"
    - "spawn"
    - "home"
    - "tpa"
    - "tpahere"
    - "tpaccept"
    - "warp"
    - "enderchest"
    - "ec"
    - "vanish"
    - "v"

# Combat logout punishment effects
logout_effects:
  # Strike lightning at player location (visual only)
  lightning: true

  # Common sounds: ENTITY_LIGHTNING_BOLT_THUNDER, ENTITY_GENERIC_EXPLODE,
  # ENTITY_WITHER_DEATH, ENTITY_ENDER_DRAGON_GROWL
  sound: "ENTITY_LIGHTNING_BOLT_THUNDER"