# Language settings (en_US, vi_VN)
language: en_US

# Combat settings
combat:
  # Duration of combat tag in seconds
  duration: 20

  # Commands that are blocked during combat
  blocked_commands:
    - "logout"
    - "tpa"
    - "tpahere"
    - "afk"
    - "spawn"
    - "tpaccept"
    - "tpacancel"
    - "rtp"
    - "warp"
    - "warp spawn"
    - "warp shop"
    - "warp worlds"
    - "warp crates"
    - "warp afk"
    - "warp auction"
    - "home"
    - "team home"
    - "enderchest"
    - "ec"
    - "vanish"
    - "v"

  # Items that are blocked during combat
  # Available items: Foods, Potions and Elytra
  disabled_items:
    - CHORUS_FRUIT
    - ELYTRA

# Ender pearl cooldown (while in combat)
enderpearl_cooldown:
  enabled: true
  # Ender pearl cooldown duration in seconds
  duration: 10

# Combat logout punishment effects
logout_effects:
  # Strike lightning at player location (visual only)
  lightning: true

  # Common sounds: ENTITY_LIGHTNING_BOLT_THUNDER, ENTITY_GENERIC_EXPLODE,
  # ENTITY_WITHER_DEATH, ENTITY_ENDER_DRAGON_GROWL
  # Or NONE to disable sound
  sound: "ENTITY_LIGHTNING_BOLT_THUNDER"

death_animation:
  enabled: true
  # Only play death animation for player kills
  only_player_kill: true
  # Enable/disable each
  # If multiple are enabled, random one will play each time
  animation:
    lightning: true
    fire_particles: false

# Combat kill rewards
kill_rewards:
  enabled: true
  commands:
    - "donutcratecore shards give %killer% 10"
  cooldown:
    # Number of days before a player can receive rewards for killing the same player again
    # Set to 0 to disable cooldown
    days: 1
    # Whether to notify players when they kill someone on cooldown
    notify: false

# Config barrier for WorldGuard no-pvp region
safezone_barrier:
  duration: 5          # How long the barrier stays in seconds
  height: 4            # How tall the barrier is
  width: 5             # How wide the barrier is