# Language settings (en_US, vi_VN)
language: en_US

# Combat settings
combat:
  # Duration of combat tag in seconds
  duration: 20

  # Commands that are blocked during combat
  blocked_commands:
    - "tpa"
    - "tpahere"
    - "afk"
    - "spawn"
    - "tpaccept"
    - "tpacancel"
    - "rtp"
    - "warp"
    - "warp spawn"
    - "warp shop"
    - "warp worlds"
    - "warp crates"
    - "warp afk"
    - "warp auction"
    - "enderchest"
    - "ec"
    - "vanish"
    - "v"

# Combat logout punishment effects
logout_effects:
  # Strike lightning at player location (visual only)
  lightning: true

  # Common sounds: ENTITY_LIGHTNING_BOLT_THUNDER, ENTITY_GENERIC_EXPLODE,
  # ENTITY_WITHER_DEATH, ENTITY_ENDER_DRAGON_GROWL
  # Or NONE to disable sound
  sound: "ENTITY_LIGHTNING_BOLT_THUNDER"

# Ender pearl cooldown (while in combat)
enderpearl_cooldown:
  enabled: true
  # Ender pearl cooldown duration in seconds
  duration: 10

# Combat kill rewards
kill_rewards:
  enabled: true
  commands:
    - "donutcratecore shards give %killer% 10"