# TIME FORMAT GUIDE
# Simple formats: 20s (20 seconds), 5m (5 minutes), 1h (1 hour)
# Complex format: 1d_2h_30m_15s (1 day, 2 hours, 30 minutes, 15 seconds)
# Units: s = seconds, m = minutes, h = hours, d = days, w = weeks, mo = months, y = years

# ADDING CUSTOM LANGUAGE
# 1. Create a new folder in the language directory
# 2. Use the files from en_US folder as a template
# 3. Modify those files as needed (messages.yml, formatting.yml,...)
# 4. Set language to your custom folder name

#---------------------------------------------------
#               Language Settings
#---------------------------------------------------
# Language setting (available: en_US, vi_VN)
language: en_US

# Enable or disable debug mode (provides verbose console output)
debug: false

#---------------------------------------------------
#              CORE COMBAT SETTINGS
#---------------------------------------------------
combat:
  # Combat tag duration
  duration: 20s

  # Command blocking mode: "blacklist" or "whitelist"
  # whitelist - blocks all commands EXCEPT those listed in 'allowed_commands'
  # blacklist - blocks only commands listed in 'blocked_commands'
  command_block_mode: "whitelist"

  # Commands allowed during combat (used in whitelist mode)
  allowed_commands:
    - "msg"
    - "r"
    - "reply"
    - "tell"
    - "w"
    - "whisper"
    - "shop"
    - "buy"
    - "sell"
    - "ah"

  # Commands blocked during combat (used in blacklist mode)
  blocked_commands:
    - "logout"
    - "tpa"
    - "tpahere"
    - "afk"
    - "spawn"
    - "tpaccept"
    - "tpacancel"
    - "rtp"
    - "warp"
    - "home"
    - "team"
    - "enderchest"
    - "ec"
    - "vanish"
    - "v"

  # If true, players kicked/banned by admins won't be punished (killed) for combat logging
  exempt_admin_kick: true

  # Disable flight (Creative fly) during combat
  disable_flight: false

  # Items blocked during combat (Foods, Potions, Elytra)
  item_restrictions:
    # Enable or disable item restrictions during combat
    enabled: false
    # Items blocked during combat (Foods, Potions, Elytra)
    disabled_items:
      - CHORUS_FRUIT
      - ELYTRA

#---------------------------------------------------
#              MOVEMENT RESTRICTIONS
#---------------------------------------------------
enderpearl_cooldown:
  # Enable/disable ender pearl cooldowns
  enabled: true

  # Cooldown duration
  duration: 10s

  # Only apply cooldowns during combat
  in_combat_only: true

  # Per-world settings (overrides global setting)
  worlds:
    minigames: false  # Example: cooldowns disabled in minigames world

#---------------------------------------------------
#                  DEATH EFFECTS
#---------------------------------------------------
death_animation:
  # Master toggle for death animations
  enabled: true

  # Only show animations for player kills
  only_player_kill: true

  # Animation types (random selection if multiple enabled)
  animation:
    lightning: true
    fire_particles: true

# ---------------------------------------------------
#                  KILL REWARDS
# ---------------------------------------------------
kill_rewards:
  # Master toggle for kill rewards
  enabled: true

  # Commands executed when player gets a kill
  # Variables: %killer% = killer's name, %victim% = victim's name
  commands:
    - donutcratecore shards give %killer% 10
  cooldown:
    # If true, killing any player puts all kill rewards on cooldown
    # If true, same_player_duration will be ignored and cooldown will be global
    # If false, cooldowns are tracked per-victim using the same_player_duration
    use_global_cooldown: false

    # How often rewards can be earned
    # Supports s (seconds), m (minutes), h (hours), d (days)
    # Examples: 30s, 5m, 2h, 1d
    duration: 1d

    # Controls cooldown behavior for killing the same player repeatedly
    # Only cooldown when killing the same player, different players are not affected
    # use_global_cooldown must be false for this to work
    use_same_player_cooldown: true
    same_player_duration: 1d

    # Permission-based cooldowns
    # When enabled, players with specific permissions get different cooldowns
    # Permission format: celestcombat.cooldown.[key] (e.g., celestcombat.cooldown.vip)
    # Permission-based cooldowns always override the default duration when applicable
    use_permission_cooldowns: false
    permissions:
      vip: 12h
      mvp: 6h
      elite: 3h

#---------------------------------------------------
#              WORLDGUARD INTEGRATION
#---------------------------------------------------
# WorldGuard's barrier for no-pvp regions
safezone_barrier:
  # Enable/disable WorldGuard integration for safezone barriers
  # This will prevent players from entering safezones while in combat
  enabled: true