#---------------------------------------------------
#              LANGUAGE SETTINGS
#---------------------------------------------------
# Available: en_US, vi_VN
# For custom languages:
# 1. Create a new folder in the language directory
# 2. Use en_US/messages.yml as a template
# 3. Modify messages.yml as needed
# 4. Set language to your custom folder name

language: en_US

# Enable or disable debug mode (provides verbose console output)
debug: false

#---------------------------------------------------
#              CORE COMBAT SETTINGS
#---------------------------------------------------
# TIME FORMAT GUIDE
# Simple formats: 20s (20 seconds), 5m (5 minutes), 1h (1 hour)
# Complex format: 1d_2h_30m_15s (1 day, 2 hours, 30 minutes, 15 seconds)
# Units: s = seconds, m = minutes, h = hours, d = days, w = weeks, mo = months, y = years

combat:
  # Combat tag duration
  duration: 20s

  # Commands blocked during combat
  blocked_commands:
    - "logout"
    - "tpa"
    - "tpahere"
    - "afk"
    - "spawn"
    - "tpaccept"
    - "tpacancel"
    - "rtp"
    - "warp"
    - "home"
    - "team"
    - "enderchest"
    - "ec"
    - "vanish"
    - "v"

  # If true, players kicked/banned by admins won't be punished (killed) for combat logging
  exempt_admin_kick: true

  # Disable flight (Creative fly) during combat
  disable_flight: true

  # Items blocked during combat (Foods, Potions, Elytra)
  item_restrictions:
    # Enable or disable item restrictions during combat
    enabled: true
    # Items blocked during combat (Foods, Potions, Elytra)
    disabled_items:
      - CHORUS_FRUIT
      - ELYTRA

#---------------------------------------------------
#              MOVEMENT RESTRICTIONS
#---------------------------------------------------
enderpearl_cooldown:
  # Enable/disable ender pearl cooldowns
  enabled: true

  # Cooldown duration
  duration: 10s

  # Only apply cooldowns during combat
  in_combat_only: true

  # Per-world settings (overrides global setting)
  worlds:
    minigames: false  # Example: cooldowns disabled in minigames world

#---------------------------------------------------
#                  DEATH EFFECTS
#---------------------------------------------------
death_animation:
  # Master toggle for death animations
  enabled: true

  # Only show animations for player kills
  only_player_kill: true

  # Animation types (random selection if multiple enabled)
  animation:
    lightning: true
    fire_particles: true

#---------------------------------------------------
#                  KILL REWARDS
#---------------------------------------------------
kill_rewards:
  # Master toggle for kill rewards
  enabled: true

  # Commands executed when player gets a kill
  # Variables: %killer% = killer's name, %victim% = victim's name
  commands:
    - "donutcratecore shards give %killer% 10"

  cooldown:
    # How often rewards can be earned (0s to disable)
    duration: 1d

    # Notify killers when victim is on cooldown
    notify: false

#---------------------------------------------------
#              WORLDGUARD INTEGRATION
#---------------------------------------------------
# WorldGuard's barrier for no-pvp regions
safezone_barrier:
  # Enable/disable WorldGuard integration for safezone barriers
  # This will prevent players from entering safezones while in combat
  enabled: true