#=============================================================
#                     CELEST COMBAT
#                      Configuration
#=============================================================
# Time Format: Use simple format like "20s" (20 seconds), "5m" (5 minutes), "1h" (1 hour)
# Complex format also supported: "1d_2h_30m_15s" (1 day, 2 hours, 30 minutes, 15 seconds)
# Units: s = seconds, m = minutes, h = hours, d = days, w = weeks, mo = months, y = years

# Language settings
language: en_US  # Available: en_US, vi_VN

#---------------------------------------------------
#              Core Combat Settings
#---------------------------------------------------
combat:
  # Duration of combat tag
  duration: 20s

  # Commands that are blocked during combat
  blocked_commands:
    - "logout"
    - "tpa"
    - "tpahere"
    - "afk"
    - "spawn"
    - "tpaccept"
    - "tpacancel"
    - "rtp"
    - "warp"
    - "home"
    - "team"
    - "enderchest"
    - "ec"
    - "vanish"
    - "v"

  # Disable flight (creative fly) during combat
  disable_flight: true

  # Items that are blocked during combat
  # Available items: Foods, Potions and Elytra
  disabled_items:
    - CHORUS_FRUIT
    - ELYTRA

#---------------------------------------------------
#              Movement Restrictions
#---------------------------------------------------
enderpearl_cooldown:
  enabled: true
  # Ender pearl cooldown duration in seconds
  duration: 10s

#---------------------------------------------------
#              Combat Logout Effects
#---------------------------------------------------
logout_effects:
  # Strike lightning at player location (visual only)
  lightning: true

  # Common sounds: ENTITY_LIGHTNING_BOLT_THUNDER, ENTITY_GENERIC_EXPLODE,
  # ENTITY_WITHER_DEATH, ENTITY_ENDER_DRAGON_GROWL
  # Or NONE to disable sound
  sound: "ENTITY_LIGHTNING_BOLT_THUNDER"

#---------------------------------------------------
#                  Kill Effects
#---------------------------------------------------
death_animation:
  enabled: true
  # Only play death animation for player kills
  only_player_kill: true

  # Enable/disable each animation type
  # If multiple are enabled, random one will play each time
  animation:
    lightning: true
    fire_particles: false

#---------------------------------------------------
#                  Kill Rewards
#---------------------------------------------------
kill_rewards:
  enabled: true

  # Commands to execute when a player gets a kill
  # %killer% = killer's name, %victim% = victim's name
  commands:
    - "donutcratecore shards give %killer% 10"

  cooldown:
    # Set to 0s to disable cooldown
    duration: 1d

    # Whether to notify players when they kill someone on cooldown
    notify: false

#---------------------------------------------------
#              WorldGuard Integration
#---------------------------------------------------
# WorldGuard's barrier for no-pvp region
safezone_barrier:
  # How long the barrier stays in seconds
  duration: 5s

  # Barrier dimensions
  height: 4
  width: 5

#---------------------------------------------------
#      ScreenShare Check System (Comming Soon)
#---------------------------------------------------
screenshare:
  # Enable or disable the screenshare system
  enabled: true

  # Maximum duration of a screenshare check section (seconds)
  # Set to 0 for unlimited time
  max_duration: 5m

  # Designated teleport location
  location:
    world: "world"
    x: 0
    y: 100
    z: 0
    yaw: 0
    pitch: 0

  # Movement restrictions
  restrictions:
    block_movement: true     # Prevent all movement
    block_commands: true     # Block all commands except those in allowed_commands
    block_chat: false        # Prevent the player from chatting
    block_inventory: true    # Prevent inventory manipulation
    invisible_to_others: true # Make screenshared player invisible to non-staff

  # Commands allowed during screenshare
  allowed_commands:
    - "msg"
    - "r"
    - "tell"

  # Actions when player disconnects during screenshare
  disconnect_actions:
    enabled: true
    commands:
      - "ban %player% Disconnected during screenshare"

  end_commands:
    # When player is clean (no cheats found)
    clean:
      - "tp %player% %previous_location%"

    # When player is caught cheating
    caught:
      - "ban %player% Caught cheating during screenshare"