name: CelesCombat
version: '${version}'
main: dev.nighter.celesCombat.CelesCombat
api-version: '1.21'
authors: [ Nighter ]
description: A simple combat logging plugin
folia-supported: true

commands:
  celescombat:
    description: Main command for CelesCombat
    usage: /celescombat
    aliases: [cc, combatlog]

permissions:
  celescombat.bypass.commands:
    description: Allows players to use commands while in combat
    default: op
  celescombat.bypass.pearlcooldown:
    description: Allows players to use enderpearls while in combat
    default: op
  celescombat.command.reload:
    description: Allows players to reload the plugin configuration
    default: op
