name: CelestCombat
version: '${version}'
main: dev.nighter.celestCombat.CelestCombat
api-version: '1.21'
authors: [ Nighter ]
description: A simple combat logging plugin
folia-supported: true

soft-depend:
  - WorldGuard

commands:
  celestcombat:
    description: Main command for CelestCombat
    usage: /celestcombat
    aliases: [cc, combatlog]

permissions:
  celestcombat.bypass.commands:
    description: Allows players to use commands while in combat
    default: op
  celestcombat.command.reload:
    description: Allows players to reload the plugin configuration
    default: op
